# Generated by Django 4.1 on 2022-08-13 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_alter_rating_movie"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ratingstar",
            options={
                "ordering": ["-value"],
                "verbose_name": "Звезда рейтинга",
                "verbose_name_plural": "Звезды рейтинга",
            },
        ),
    ]
